# Generated by Django 5.2.3 on 2025-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355, verbose_name='Название')),
                ('price_with_discount', models.PositiveIntegerField(verbose_name='Цена без скидки')),
                ('full_price', models.PositiveIntegerField(default=0, verbose_name='Полная цена')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('feedbacks', models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'unique_together': {('name',)},
            },
        ),
    ]
